language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

cache: pip

install:
  - pip install -U pip setuptools
  - pip install -e .[ci]

script:
  - flake8 ./
  - pytest --cov --cov-report term-missing:skip-covered

after_success:
  - coveralls
